FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD csa-twitter-search-1.0.0-SNAPSHOT.jar TwitterSearchMicroservice.jar
EXPOSE 9020
RUN sh -c 'touch /TwitterSearchMicroservice.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -D -jar /TwitterSearchMicroservice.jar" ]